name: KenyaEMR CI

'on':
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./dev-build.sh
          sh ./dev-build.sh
        shell: bash
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: |
            frontend
      - name: Upload frontend to server
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          port: '${{ secrets.PORT }}'
          source: ./frontend/
          target: /home/developers
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          port: '${{ secrets.PORT }}'
          script: >-
            mv /var/lib/OpenMRS/frontend /var/lib/OpenMRS/frontend_old && mv
            /home/developers/frontend /var/lib/OpenMRS/frontend && rm -rf
            /var/lib/OpenMRS/frontend_old
    

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
      - name: Run production build script
        run: |
          chmod +x ./prod-build.sh
          sh ./prod-build.sh
        shell: bash
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: |
            frontend
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./frontend.zip
          asset_name: frontend
          asset_content_type: application/ 